<?php

use Vitalii\Exam\Api\Data\FruitInterface;
use Vitalii\Exam\Block\Fruits;
use Vitalii\Exam\Model\FruitModel;

/**
 * @var Fruits $block
 * @var FruitInterface[]|FruitModel[] $fruits
 */
$fruits = $block->getFruits();

?>

<table>

    <tr>
        <th class="entity-id">
            <?= __("Entity Id"); ?>
        </th>
        <th class="fruit-name">
            <?= __("Fruit Name"); ?>
        </th>
        <th class="color-id">
            <?= __("Color Id"); ?>
        </th>
        <th class="description">
            <?= __("Description"); ?>
        </th>
        <th class="weight">
            <?= __("Weight"); ?>
        </th>
        <th class="taste">
            <?= __("Taste"); ?>
        </th>
        <th class="price">
            <?= __("Price"); ?>
        </th>
        <th class="created-at">
            <?= __("Created At"); ?>
        </th>
        <th class="link">
            <?= __("Link"); ?>
        </th>
    </tr>

    <?php if (!empty($fruits)): ?>

        <?php foreach ($fruits as $fruit): ?>
            <tr>
                <td>
                    <?= $fruit->getId(); ?>
                </td>
                <td>
                    <?= $fruit->getFruitName(); ?>
                </td>
                <td>
                    <?= $fruit->getColorId(); ?>
                </td>
                <td>
                    <?= $fruit->getDescription(); ?>
                </td>
                <td>
                    <?= $fruit->getWeight(); ?>
                </td>
                <td>
                    <?= $fruit->getTaste(); ?>
                </td>
                <td>
                    <?= $fruit->getPrice(); ?>
                </td>
                <td>
                    <?= $fruit->getCreatedAt(); ?>
                </td>
                <td>
                    <a  href="<?= $block->getUrl('exam_route'); ?>">
                        <?= __('Go Back'); ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>

    <?php else: ?>
        <div class="message">
            <h1 class="message-error error message">
                <?= __("There are no fruits found."); ?>
            </h1>
        </div>

    <?php endif; ?>

</table>
