<?php

use Vitalii\Test\Model\CarCustomerModel;
use Vitalii\Test\ViewModel\ExtraInfo;

/** @var \Vitalii\Test\Block\CarCustomers $block */
$blockName = $block->getNameInLayout();
$string = $block->getData('custom_string');
$array = $block->getData('custom_array');

/** @var ExtraInfo $viewModel */
$viewModel = $block->getData('our_view_model');

/** @var \Vitalii\Test\Model\ResourceModel\CarCustomer\Collection $carCustomersCollection */
$carCustomersCollection = $block->getCarCustomersCollection();
?>

<h1 class="my-block">My Custom Information from theme: my-template.phtml!</h1>
<h2 class="my-block">My Custom String is: "<?= $string ?>"</h2>
<h3 class="my-block">My Custom Array first_key is: "<?= $array['array_key_one'] ?>"</h3>
<h3 class="my-block">My Custom Array second_key is: "<?= $array['array_key_two'] ?>"</h3>
<?php if ($viewModel && $viewModel->getCurrentDate()): ?>
    <h3 class="my-block"><?= $viewModel->getCurrentDate() ?></h3>
<?php endif; ?>
<div class="container">
    <?php foreach ($carCustomersCollection as $carCustomer): ?>
        <?php /** @var CarCustomerModel $carCustomer */ ?>
        <div class="car-customer-id-<?= $carCustomer->getId() ?>">
            <h4 class="entity-id">EntityId: <?= $carCustomer->getId() ?></h4>
            <h3 class="email">Email: <?= $carCustomer->getEmail() ?></h3>
            <h5 class="user-name">UserName: <?= $carCustomer->getName() ?></h5>
            <h6 class="some-id">SomeId: <?= $carCustomer->getSomeId() ?></h6>
            <h6 class="created-at">CreatedAt: <?= $carCustomer->getCreatedAt() ?></h6>
            <p class="link">
                <a class="read-more" href="<?= $block->getUrl('my_route/index/cars', ['user_id' => $carCustomer->getId()]) ?>">See Customer Cars</a>
            </p>
        </div>
    <?php endforeach; ?>
</div>
